version: '3.9'

services:
  db:
    image: postgres:16
    container_name: helpiguacudb
    restart: unless-stopped
    environment:
      POSTGRES_USER: helpiguacu
      POSTGRES_PASSWORD: helpiguacu
      POSTGRES_DB: helpiguacu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
